### ISSUE TITLE
mso_schema_template_contract_filter error message

### ISSUE THREAD

**Issue by angelogemma** [CiscoDevNet/ansible-mso#300] opened 2022-11-16 18:19 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description
Hi Team, I'm not able to create a contract on MSO via ansible script.

I got always the reported error message.

### Affected Module Name(s):
mso_schema_template_contract_filter

### MSO version and MSO Platform
Cisco Nexus Dasjboard Version 2.2(2d)
* V 4.0.2(i) ND-based
 (Cisco Nexus Dashboard Orchestrator Sandbox Lab)

### APIC version and APIC Platform for Site Level Resources

APIC 5.2(1g) (Cisco Nexus Dashboard Orchestrator Sandbox Lab)

### Collection versions

* cisco.mso 2.1.0

### Output/ Error message

fatal: [10.10.20.60]: FAILED! => {
    "changed": true,
    "current": {
        "action": "permit",
        "contractFilterType": "bothWay",
        "contractScope": "context",
        "directives": [
            "none"
        ],
        "displayName": "TEST5",
        "filterRef": {
            "filterName": "WEBFilter",
            "schemaId": "6374c71cd2ae362bf0b1f022",
            "templateName": "TEN-STRETCH"
        },
        "filterType": "both-way"
    },
    "data": [
        {
            "op": "add",
            "path": "/templates/TEN-STRETCH/contracts/-",
            "value": {
                "displayName": "TEST5",
                "filterType": "bothWay",
                "name": "TEST5",
                "scope": "context"
            }
        },
        {
            "op": "add",
            "path": "/templates/TEN-STRETCH/contracts/TEST5/filterRelationships/-",
            "value": {
                "action": "permit",
                "contractFilterType": "bothWay",
                "contractScope": "context",
                "directives": [
                    "none"
                ],
                "displayName": "TEST5",
                "filterRef": {
                    "filterName": "WEBFilter",
                    "schemaId": "6374c71cd2ae362bf0b1f022",
                    "templateName": "TEN-STRETCH"
                },
                "filterType": "both-way"
            }
        }
    ],
    "info": {
        "body": {
            "code": 400,
            "message": "add operation does not apply: doc is missing path: \"/templates/0/contracts/1/filterRelationships/-\": missing value"
        },
        "connection": "close",
        "content-language": "en",
        "content-length": "141",
        "content-type": "application/json",
        "error": {
            "code": -1,
            "message": {
                "code": 400,
                "message": "add operation does not apply: doc is missing path: \"/templates/0/contracts/1/filterRelationships/-\": missing value"
            }
        },
        "method": "PATCH",
        "msg": "OK (141 bytes)",
        "server": "nginx",
        "status": 400,
        "strict-transport-security": "max-age=31536000; includeSubDomains",
        "url": "https://10.10.20.60:443/mso/api/v1/schemas/6374c71cd2ae362bf0b1f022?validate=false",
        "x-ratelimit-limit": "-1",
        "x-ratelimit-remaining": "-1",
        "x-ratelimit-reset": "1559582945"
    },
    "invocation": {
        "module_args": {
            "action": "permit",
            "contract": "TEST5",
            "contract_display_name": null,
            "contract_filter_type": "both-way",
            "contract_scope": null,
            "description": null,
            "filter": "WEBFilter",
            "filter_directives": null,
            "filter_schema": "TEN-PROD",
            "filter_template": "TEN-STRETCH",
            "filter_type": "both-way",
            "host": "10.10.20.60",
            "login_domain": null,
            "output_level": "normal",
            "password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
            "port": null,
            "priority": null,
            "qos_level": null,
            "schema": "TEN-PROD",
            "state": "present",
            "template": "TEN-STRETCH",
            "timeout": 30,
            "use_proxy": null,
            "use_ssl": null,
            "username": "admin",
            "validate_certs": false
        }
    },
    "msg": "MSO Error 400: add operation does not apply: doc is missing path: \"/templates/0/contracts/1/filterRelationships/-\": missing value",
    "payload": {
        "code": 400,
        "message": "add operation does not apply: doc is missing path: \"/templates/0/contracts/1/filterRelationships/-\": missing value"
    },
    "status": 400
}

*

### Expected Behavior

Contract creation with filter associated
*

### Actual Behavior

Error
*

### Playbook tasks to Reproduce

---
- name: ENSURE APPLICATION CONFIGURATION EXISTS
  hosts: mso
  connection: local
  gather_facts: False

  vars:
    - tenant: "TEN"
    - schema: "TEN-PROD"
    - template: "TEN-STRETCH"

  tasks:

    - name: RICERCA SCHEMA ID
      cisco.mso.mso_schema:
        host: "{{ inventory_hostname }}"
        username: "{{ username }}"
        password: "{{ password }}"
        validate_certs: False
        schema: "{{ schema }}"
        state: "query"
      register: schemaID

    - name: CREAZIONE CONTRACTS
      cisco.mso.mso_schema_template_contract_filter:
         host: "{{ inventory_hostname }}"
         username: "{{ username }}"
         password: "{{ password }}"
         validate_certs: False
         state: "present"
         schema: "{{ schema }}"
         template: "{{ template }}"
         contract: "TEST5"
         filter: "WEBFilter"
         filter_template: "{{ template }}"
         filter_schema: "{{ schema }}"
         action: "permit"
         filter_type: "both-way"

    - name: DEPLOY DEL TEMPLATE
      cisco.mso.mso_rest:
        host: "{{ inventory_hostname }}"
        username: "{{ username }}"
        password: "{{ password }}"
        validate_certs: False
        path: /mso/api/v1/task
        method: post
        content: 
          {
            "schemaId":"{{ schemaID.current.id }}",
            "templateName":"{{ template }}",
            "isRedeploy":true,
            "_updateVersion":0
          }

*
### Important Factoids

I tried to set/swap/change parameters of the tasks, but no chances to work.

### References

* #0000

**Comment by akinross** [comment] 2022-11-18 09:37
Hi @angelogemma,

Thank you for raising this issue, this will be solved in newer release of NDO. We are aware that multiple modules are not working anymore for NDO4.0. Changes have been made to the NDO4.0 API which are impacting the collection. We are currently working on fixes to address the issues.

**Comment by mupett** [comment] 2022-11-24 16:46
Hello,
what is the forecast timeline for this fix for NDO 4.0?

Thanks.
Luca

**Comment by akinross** [comment] 2022-12-10 09:59
Closing because this is duplicate of / related to issue #298 which will be resolved in https://github.com/CiscoDevNet/ansible-mso/pull/306 and when NDO 4 fixes are made

**Closed by akinross** 2022-12-10 09:59 UTC
Labels: bug
