### ISSUE TITLE
Implement bulk EPG static path binding module

### ISSUE THREAD

**Issue by cpaggen** [CiscoDevNet/ansible-mso#344] opened 2023-03-10 09:20 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description
Several customers have expressed interest in having a NDO module similar to APIC's cisco.aci.aci_bulk_static_binding_to_epg [doc](https://docs.ansible.com/ansible/latest/collections/cisco/aci/aci_bulk_static_binding_to_epg_module.html)

The goal is to speed up the deployment of large amounts of EPG static path bindings. Deploying those one by one today takes several seconds per iteration, often leading to complete deployments times exceeding 30 minutes for large configurations. The corresponding ACI bulk module shows a dramatic performance improvement (usually under 2 seconds regardless of the number of bindings) over a sequential approach whose completion time is a function of the number of bindings.

**Comment by lhercot** [comment] 2023-03-10 17:57
Duplicate of #297

**Closed by lhercot** 2023-03-10 17:57 UTC
Labels: enhancement
