### ISSUE TITLE
[mso_schema_template_anp_epg] Bad Request: (0)(0)/epgs(0)(0)/contractRef/schemaId error.path.missing"

### ISSUE THREAD

**Issue by ysolan** [CiscoDevNet/ansible-mso#82] opened 2020-07-20 14:43 UTC
Hello,

with collection v0.0.7
message: "Bad Request: (0)(0)/epgs(0)(0)/contractRef/schemaId error.path.missing"
[mso_task.txt](https://github.com/CiscoDevNet/ansible-mso/files/4948354/mso_task.txt)
[mso_current_schema.txt](https://github.com/CiscoDevNet/ansible-mso/files/4948355/mso_current_schema.txt)

**Comment by lhercot** [comment] 2020-07-20 15:13
Hi ysolan,

I am trying to reproduce your issue.
Just for my understanding, are yout trying to query a non-existing EPG?
I am just checking because it seems that the EPG you are querying for (EPG VLAN_961_EPG) is not present in Template LAB_PODA (used in your task) but is present in Template LAB_ALL.

Could you also capture the complete error output from the ansible run and attach it to this issue?

**Comment by ysolan** [comment] 2020-07-21 09:18
Hi @lhercot ,

here's the correct task and output error.
[mso_task.txt](https://github.com/CiscoDevNet/ansible-mso/files/4952470/mso_task.txt)
[mso_error_output.txt](https://github.com/CiscoDevNet/ansible-mso/files/4952471/mso_error_output.txt)

**Comment by lhercot** [comment] 2020-07-21 09:32
Hi @ysolan ,
Which version of MSO are you using?

**Comment by lhercot** [comment] 2020-07-21 12:28
Good catch! I managed to reproduce the issue with the updated task you provided.
You can have a look at PR #83 on the fix for it.
I also added the same QA test to all the modules that handles contracts to be sure but the other ones already had the fix for it.
This will be part of v0.0.8 which should be out today or tomorrow.

**Closed** 2020-07-21 17:37 UTC
